spring:
  cloud:
    stream:
      bindings:
        player-created:
          destination: player-created # exchange that will be created
          group: social # queue that will be created and binded to the exchange
      rabbit:
        bindings:
          player-created:
            consumer:
              auto-bind-dlq: true
              dead-letter-queue-name: dlq.player-created.social
  rabbitmq:
    host: porpoise.rmq.cloudamqp.com
    virtual-host: mrwninmq
    username: mrwninmq
    password: s4UPswpVYk_G2y8ONH3zr57CalYthaXJ