spring:
  cloud:
    stream:
      bindings:
        player-created:
          destination: player-created # exchange that will be created
          group: social # queue that will be created and binded to the exchange
        event-created:
          destination: event-created
          group: social
  rabbitmq:
    host: porpoise.rmq.cloudamqp.com
    virtual-host: mrwninmq
    username: mrwninmq
    password: s4UPswpVYk_G2y8ONH3zr57CalYthaXJ